FROM condaforge/mambaforge:23.3.1-1 as build

RUN conda install -c conda-forge conda-merge conda-pack
RUN wget https://raw.githubusercontent.com/QCDIS/NaaVRE/1031-cant-install-climwin/docker/lter-life/environment.yaml
RUN mamba env create -f environment.yaml

RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack


FROM ubuntu:24.04 as runtime

COPY --from=build /venv/ /venv/

RUN du -sh /venv
# test climwin
COPY test_climwin.R .