FROM condaforge/mambaforge:23.3.1-1 as build

RUN conda install -c conda-forge conda-merge conda-pack
RUN wget https://raw.githubusercontent.com/QCDIS/NaaVRE/1031-cant-install-climwin/docker/lter-life/environment.yaml
RUN mamba env create -f environment.yaml

RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack


FROM rhub/r-minimal:4.4 as runtime

COPY --from=build /venv/ /venv/

ENV PATH=/venv/bin:$PATH
SHELL ["/bin/bash", "--login", "-c"]
SHELL ["/bin/bash", "-c"," source /venv/bin/activate;"]
RUN echo "source /venv/bin/activate" >> ~/.bashrc
RUN source /venv/bin/activate


# test climwin
COPY test_climwin.R .
RUN Rscript test_climwin.R
RUN rm test_climwin.R