FROM condaforge/mambaforge:23.3.1-1 as build

RUN conda install -c conda-forge conda-merge conda-pack
RUN wget https://raw.githubusercontent.com/QCDIS/NaaVRE/main/docker/lter-life/environment.yaml
RUN mamba env create -f environment.yaml

RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack


FROM ubuntu:24.04 as runtime

COPY --from=build /venv/ /venv/

# test climwin
COPY install-and-load-the-climwinb-packages-dev-user-name-at-domain-com.R .
COPY consume-climwin-dev-user-name-at-domain-com.R .
